---
title: "Praca domowa 1"
author: "Paweł Rzepiński"
output: html_document
---

## Data

Source: "Price of flats fell in England last year, says Land Registry" at https://www.bbc.com/news/business-47223988

```{r}
df <- read.table(
  header = T,
  sep = ",",
  text = '
"region", "price_change"
"N. Ireland","5.5"
"West Midlands","5.2"
"Wales", "5.2"
"Yorkshire and The Humber","4.2"
"East Midlands","4.2"
"North West","3.5"
"South West","2.9"
"Scotland","2.4"
"South East","1.2"
"East","0.2"
"London","-0.6"
"North East","-1.0"')
```

## Plot

```{r, echo=FALSE}
library(ggplot2)

ggplot(data = df, aes(x = reorder(region, price_change), y = price_change)) + 
  geom_bar(stat="identity", fill="#1380A1") +
  scale_y_continuous(breaks = seq(-1, 6, by = 1), limits = c(-1,6)) +
  coord_flip() + 
  geom_hline(yintercept = 0, size = 1) +
  labs(title="How house prices changed",
       subtitle="Annual percentage change") +
  theme(plot.title = element_text(size = 22, face = "bold"),
        plot.subtitle = element_text(size = 20),
        axis.title = element_blank(),
        axis.text = element_text(size = 16),
        axis.ticks = element_blank(),
        panel.grid.major.x = element_line(color = "#cbcbcb"),
        panel.background = element_blank())
```
