---
output:
  html_document: default
  pdf_document: default
---

```{r, echo = FALSE}
# Wyjściówka

# Narysowac mape Europy (filter(long > -30, lat > 30)) z wyszczegolnionymi krajami,
# podpisac kazdy kraj i w nawiasie napisac ile ma nuts poziomu 1, np "PL 7".
```

# Wyjściówka nr 2
## Tymoteusz Makowski

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library('ggplot2')
library('eurostat')
library('dplyr')

lp <- get_eurostat_geospatial(output_class = "df", resolution = "60", nuts_level = "all")

nuts_count <- lp %>%
    filter(long > -30, lat > 30, LEVL_CODE == 1) %>%
    group_by(CNTR_CODE) %>%
    count()

names_df <- filter(lp, long > -30, lat > 30, LEVL_CODE == 0) %>%
  group_by(CNTR_CODE) %>% 
  summarise(long = mean(long),
            lat = mean(lat))

filter(lp, long > -30, lat > 30, LEVL_CODE == 0) %>%
  group_by(CNTR_CODE) %>% 
  ggplot(aes(x = long, y = lat, group = group, fill = CNTR_CODE)) + 
  geom_polygon(color = "black") +
  geom_text(data = names_df, aes(x = long, y = lat, label = sprintf("%s (%d)", CNTR_CODE, nuts_count %>% filter(CNTR_CODE == CNTR_CODE) %>% pull(n))), inherit.aes = FALSE) +
  coord_map() + 
  scale_fill_discrete(guide = FALSE)+
  theme_classic()
```