---
title: "Praca Domowa 2"
author: "Aleksandra Miesi¹c"
date: "10 marca 2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
```

## Dane

Dane liczbowe z pracy domowej Artura Gajowniczka.

```{r, echo = FALSE}
console <- c("Nintendo Switch", "PlayStation 4", "Nintendo 3DS", "PS Vita", "Xbox One")
consoles_sold <- c(3482388, 1695227, 566420, 181728, 15339)
consoles_sold_pr <- round((consoles_sold/sum(consoles_sold))*100,digits = 1)
df<- data.frame(console, consoles_sold,consoles_sold_pr)
df
```

## Wykres Artura

```{r, echo=FALSE}

ggplot(df, aes(x=console, y=consoles_sold)) + 
  geom_bar(stat="identity") + 
  ggtitle("Sprzeda¿ konsoli w Japonii w 2018 r.")+
  labs(y="Liczba sprzedanych konsoli", x = "Konsola")
```

## Poprawiony wykres


```{r, echo = FALSE, fig.width=10}
cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#009E73",
          "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
ggplot(df, aes(x=console,y =consoles_sold_pr , fill=console))+ scale_fill_manual(values = cbp1) + geom_text(aes(label=paste0(consoles_sold_pr,"%")), vjust=-0.3, size=5)+
  geom_bar(stat = "identity") + scale_x_discrete(limits = console)+
  ggtitle("Sprzeda¿ konsoli w Japonii w 2018 r.")+
  labs(y="Procent sprzedanych konsoli", x = "Konsola",fill='Rodzaje konsoli')+ theme(axis.text.x=element_text(size = 12),axis.text.y=element_text(size = 12))

```

