---
title: "Consequences of bad data visualization - feel it on your own skin..."
author: "Marcin Dardziński, Stanisław Pawlak, Paweł Rzepiński, Ryszard Szymański"
output:
  slidy_presentation:
    css: style.css
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(magrittr)
source("./builder.R")
```


## Pie Chart madness

```{r echo=FALSE}
pie_chart <- ggplot(mtcars, aes(x = "", y = cyl, fill = cyl)) +
  geom_bar(stat="identity") +
  coord_polar("y", start=0)

bar_chart <- ggplot(mtcars, aes(x=cyl, fill=cyl)) +
  geom_bar()

builder <- create_visualization_case_builder() %>% 
  add_good_plot(bar_chart) %>% 
  add_bad_plot(pie_chart) %>% 
  add_qa_case("What is the value for xxx?", 30) %>% 
  add_qa_case("What is the value for yyy?", 60) %>% 
  add_qa_case("What is the value for zzz?", 30) %>% 
  add_qa_case("What is the value for aaa?", 60)

app <- build(builder)
shinyApp(app$ui, app$server)
```

## Pie char madness returns

```{r echo=FALSE}
pie_chart <- ggplot(mtcars, aes(x = "", y = cyl, fill = cyl)) +
  geom_bar(stat="identity") +
  coord_polar("y", start=0)

bar_chart <- ggplot(mtcars, aes(x=cyl, fill=cyl)) +
  geom_bar()

builder <- create_visualization_case_builder() %>% 
  add_good_plot(bar_chart) %>% 
  add_bad_plot(pie_chart) %>% 
  add_qa_case("What is the value for xxx?", 30) %>% 
  add_qa_case("What is the value for aaa?", 60)

app <- build(builder)
shinyApp(app$ui, app$server)
```

## Stacked plots
```{r echo=FALSE}
source('stacked.R')

app <- stacked_example() %>% build()
shinyApp(app$ui, app$server)
```

## Double axes
```{r echo=FALSE, message=FALSE}

pd <- read.csv("plot-double_axes.csv")

to_trillion <- function(b) { paste0(round(b / 10^12, 0), "T")}

ratio <- max(pd$World) / max(pd$Germany)

bad_plot <- ggplot() + 
  geom_line(mapping = aes(x = pd$Year, y = pd$World), color = "grey") +
  geom_line(mapping = aes(x = pd$Year, y = pd$Germany*ratio), color = "blue") + 
  scale_y_continuous(name = "World", labels = to_trillion,
                     sec.axis = sec_axis(~./ratio, name = "Germany", labels = to_trillion)) + 
  xlab("Year") +
  theme(
    axis.title.y = element_text(color = "grey"),
    axis.title.y.right = element_text(color = "blue"))

# So while the chart looks likethe German GDP and the global GDP go up at roughly the same rate (at least until 2014), 
# they don’t. The global GDP increased by 80% until 2014; the GDP of Germany by 40%.

library(dplyr)
library(tidyr)
new_pd <- mutate(pd) %>%
  mutate(Germany_Change = Germany/Germany[1] * 100 - 100, World_Change = World/World[1] * 100 - 100) %>%
  ungroup %>%
  select(Year, Germany_Change, World_Change) %>% 
  gather(key, value, Germany_Change, World_Change)

good_plot <- ggplot(new_pd, aes(x=Year, y=value, colour=key)) +
  geom_line()

builder <- create_visualization_case_builder() %>% 
  add_good_plot(good_plot) %>% 
  add_bad_plot(bad_plot) %>% 
  add_qa_case("How much global GDP increased until 2014?", 80) %>% 
  add_qa_case("How much GDP of Germany increased until 2014?", 40)


app <- build(builder)
shinyApp(app$ui, app$server)
```

## Area plot

```{r echo=FALSE}
data <- data.frame(name=c("United States", "China", "Japan", "Germany", "France"),
                   gdp=c(14.6,5.7,5.3,3.3,2.5) )

bad_plot <- ggplot(data, aes(x=name, y=1, size=gdp)) +
  geom_point(color="#69b3a2") +
  geom_text(aes(label=name), size=3) +
  scale_size_continuous(range=c(5,29.2)) +
  theme_void() +
  theme(
    legend.position="none"
  ) +
  ylim(0.9,1.1)

good_plot <- ggplot(data, aes(x=reorder(name, -gdp), y=gdp)) +
  geom_bar(stat="identity", fill="#69b3a2")

# US GDP vs China GDP? How many times more?
# Ordering, area vs radius for circle plots

builder <- create_visualization_case_builder() %>% 
  add_bad_plot(bad_plot) %>% 
  add_good_plot(good_plot) %>% 
  add_qa_case("How many times US GDP is larger than China's?", 2.56)
  
  
app <- build(builder)
shinyApp(app$ui, app$server)
```
